In [6]:
import numpy as np
import scipy as sp

In [12]:
def block_lanczos(H,V,q,reorth=0):
    
#     H is dxd, V is d x b, b is block size
#     @ is normal matrix multiplication
#     q is the number of iterations
    Z = np.copy(V)
    d,b = Z.shape
    
    M = [ np.zeros((b,b),dtype=H.dtype) ]*q
    B = [ np.zeros((b,b),dtype=H.dtype) ]*(q+1)
    
    Q = np.zeros((d,b*(q+1)),dtype=H.dtype)

#     if not assume orthogonal then use qr to orthogonalize 
    Q[:,0:b],B[0] = np.linalg.qr(Z)
    for k in range(0,q):
        
#         Qk is the next column of blocks
        Qk = Q[:,k*b:(k+1)*b]
#         Q_k-1 = 0 when k = 0, so Z = H@Qk.
        if k > 0
            Qkm1 = Q[:,(k-1)*b:k*b]
        else 
            Qkm1 = np.zeros((q, b))
            
#         why conjugate and transpose?
        Z = H@Qk - Qkm1@(B[k].conj().T) if k > 0 else H@Qk
        
        if reorth>k:
            Z -= Q[:,:k*b]@(Q[:,:k*b].conj().T@Z)
            Z -= Q[:,:k*b]@(Q[:,:k*b].conj().T@Z)

        M[k] = Qk.conj().T@Z
        Z -= Qk@M[k]
        
        Q[:,(k+1)*b:(k+2)*b],B[k+1] = np.linalg.qr(Z)
    
    return Q,M,B

In [ ]:
def get_block_tridiag(M,R):

    q = len(M)
    b = len(M[0])
    
    T = np.zeros((q*b,q*b),dtype=M[0].dtype)

    for k in range(q):
        T[k*b:(k+1)*b,k*b:(k+1)*b] = M[k]

    for k in range(q-1):
        T[(k+1)*b:(k+2)*b,k*b:(k+1)*b] = R[k]
        T[k*b:(k+1)*b,(k+1)*b:(k+2)*b] = R[k].conj().T
        
    return T

In [39]:
A = np.random.rand(2, 3)
B = np.random.rand(3, 3)

A = A*10
B = B*10

In [40]:
A = np.round(A)
B = np.round(B)

In [48]:
A

array([[4., 5., 2.],
       [5., 9., 8.]])

In [42]:
A.shape
B.shape

(3, 3)

In [43]:
A@B

array([[ 29.,  63.,  59.],
       [ 39., 142., 148.]])

In [45]:
Q, R = np.linalg.qr(A)

In [50]:
Q

array([[-0.62469505, -0.78086881],
       [-0.78086881,  0.62469505]])